--[[
    AutoDoor building objects (server side, same pattern as vanilla
    ISDoubleDoor / GreggiesGarageDoors).
    Defines:
      - ISAutoGarageDoor : 3-tile roller garage door built from vanilla
        walls_garage_* sprites (native GarageDoor tile property chains them).
      - ISAutoFenceGate  : single-tile fence gate built from vanilla
        fixtures_doors_fences_01_* sprites (doorW/doorN/doorTrans properties).
    Every built door gets a random key id; the remote control and the key
    generated by AutoDoor.grantAccessories are paired to that id.
]]

require "BuildingObjects/ISBuildingObject"
require "BuildingObjects/ISBuildUtil"
require "AutoDoor/AutoDoorDoorLib"

-- ============================================================
-- ISAutoGarageDoor
-- ============================================================

ISAutoGarageDoor = ISBuildingObject:derive("ISAutoGarageDoor")

function ISAutoGarageDoor:create(x, y, z, north, sprite)
    local cell = getWorld():getCell()
    local square = cell:getGridSquare(x, y, z)
    if not square then return end
    local xa, ya, za = self:getPartPos(square, north, 2)
    local xb, yb, zb = self:getPartPos(square, north, 3)
    local sprites = north and self.style.spriteN or self.style.spriteW
    self:addDoorPart(x, y, z, north, sprites[1], 1)
    self:addDoorPart(xa, ya, z, north, sprites[2], 2)
    self:addDoorPart(xb, yb, z, north, sprites[3], 3)
end

function ISAutoGarageDoor:addDoorPart(x, y, z, north, sprite, index)
    local cell = getWorld():getCell()
    self.sq = cell:getGridSquare(x, y, z)
    if not self.sq then return end
    if self:partExists(self.sq, index) then return end
    self.javaObject = IsoDoor.new(cell, self.sq, sprite, north)
    buildUtil.setInfo(self.javaObject, self)
    self:overrideModData(index)
    self.javaObject:setMaxHealth(self:getHealth())
    self.javaObject:setHealth(self.javaObject:getMaxHealth())
    self.javaObject:setBreakSound("MetalDoorBreak")
    self.sq:AddSpecialObject(self.javaObject)
    if index == 1 then
        buildUtil.consumeMaterial(self)
        AutoDoor.grantAccessories(getSpecificPlayer(self.player), self.keyId)
    end
    self.javaObject:getModData().autoDoor = true
    self.javaObject:setKeyId(self.keyId)
    self.javaObject:transmitCompleteItemToClients()
end

-- Distribute the build materials over the 3 parts so dismantling each
-- part returns the right share (mirrors vanilla ISDoubleDoor).
function ISAutoGarageDoor:overrideModData(spriteIndex)
    local buildMaterials = self.javaObject:getBuildMaterials()
    local buildMaterials2 = copyTable(buildMaterials)
    for itemFullType, v in pairs(buildMaterials2) do
        local count = tonumber(v)
        if itemFullType == "Base.Doorknob" then
            if spriteIndex == 1 then
                buildMaterials[itemFullType] = "1"
            else
                buildMaterials[itemFullType] = nil
            end
        else
            local count2 = math.floor(count / 3 + 0.01)
            if (count % 3 ~= 0) and (spriteIndex <= count % 3) then
                count2 = count2 + 1
            end
            if count2 == 0 then
                buildMaterials[itemFullType] = nil
            else
                buildMaterials[itemFullType] = tostring(count2)
            end
        end
    end
end

function ISAutoGarageDoor:getPartPos(square, north, index)
    local x = square:getX()
    local y = square:getY()
    local z = square:getZ()
    if north then
        x = x + (index - 1)
    else
        y = y - (index - 1)
    end
    return x, y, z
end

function ISAutoGarageDoor:partExists(square, index)
    if not square then return false end
    local sprites = self.north and self.style.spriteN or self.style.spriteW
    local spriteName = sprites[index]
    local objects = square:getSpecialObjects()
    for i = 1, objects:size() do
        local object = objects:get(i - 1)
        if instanceof(object, "IsoDoor") and
            object:getNorth() == self.north and
            not object:IsOpen() and
            object:getSprite() and object:getSprite():getName() == spriteName then
            return true
        end
    end
    return false
end

function ISAutoGarageDoor:isValid(square)
    if not self:haveMaterial(square) then return false end
    if not square:hasFloor(self.north) then return false end
    if square:isVehicleIntersecting() then return false end
    if not self:partExists(square, 1) and not square:isFreeOrMidair(false) then
        return false
    end
    local xa, ya, za = self:getPartPos(square, self.north, 2)
    local xb, yb, zb = self:getPartPos(square, self.north, 3)
    local squareA = getCell():getGridSquare(xa, ya, za)
    local squareB = getCell():getGridSquare(xb, yb, zb)
    if (not squareA) or (not squareB) then return false end
    if not self:partExists(squareA, 2) and not buildUtil.canBePlace(self, squareA) then return false end
    if not self:partExists(squareB, 3) and not buildUtil.canBePlace(self, squareB) then return false end
    if squareA:isSomethingTo(square) then return false end
    if squareB:isSomethingTo(squareA) then return false end
    if buildUtil.stairIsBlockingPlacement(square, true, self.north) then return false end
    if buildUtil.stairIsBlockingPlacement(squareA, true, self.north) then return false end
    if buildUtil.stairIsBlockingPlacement(squareB, true, self.north) then return false end
    return true
end

function ISAutoGarageDoor:render(x, y, z, square)
    local sprites = self.north and self.style.spriteN or self.style.spriteW
    for index = 1, 3 do
        local px, py, pz = x, y, z
        if index > 1 then
            px, py, pz = self:getPartPos(square, self.north, index)
        end
        local targetSquare = getCell():getGridSquare(px, py, pz)
        if targetSquare == nil and getWorld():isValidSquare(px, py, pz) then
            targetSquare = IsoGridSquare.new(getCell(), nil, px, py, pz)
            getCell():ConnectNewSquare(targetSquare, false)
        end
        if targetSquare and not self:partExists(targetSquare, index) then
            local sprite = IsoSprite.new()
            sprite:LoadSingleTexture(sprites[index])
            local free = true
            if index == 1 then
                free = self:isValid(square)
            else
                free = buildUtil.canBePlace(self, targetSquare)
                    and not targetSquare:isSomethingTo(getCell():getGridSquare(
                        self:getPartPos(square, self.north, index - 1)))
                    and not buildUtil.stairIsBlockingPlacement(targetSquare, true, self.north)
            end
            if free then
                sprite:RenderGhostTile(px, py, pz)
            else
                sprite:RenderGhostTileRed(px, py, pz)
            end
        end
    end
end

function ISAutoGarageDoor:getHealth()
    return self.style.health
end

function ISAutoGarageDoor:new(styleIndex)
    local o = {}
    setmetatable(o, self)
    self.__index = self
    o:init()
    o.style = AutoDoor.GARAGE_DOOR_STYLES[styleIndex]
    o:setSprite(o.style.spriteW[1])
    o.northSprite = o.style.spriteN[1]
    o.isDoor = true
    o.isWallLike = true
    o.thumpDmg = 5
    o.name = getText("IGUI_AutoDoor_GarageDoor")
    o.keyId = ZombRand(100000, 999999)
    o.modData = AutoDoor.buildModData(o.style.materials)
    return o
end

-- ============================================================
-- ISAutoFenceGate
-- ============================================================

ISAutoFenceGate = ISBuildingObject:derive("ISAutoFenceGate")

function ISAutoFenceGate:create(x, y, z, north, sprite)
    local cell = getWorld():getCell()
    self.sq = cell:getGridSquare(x, y, z)
    if not self.sq then return end
    if self:partExists(self.sq) then return end
    local spriteName = north and self.style.northSprite or self.style.sprite
    self.javaObject = IsoDoor.new(cell, self.sq, spriteName, north)
    buildUtil.setInfo(self.javaObject, self)
    self.javaObject:setMaxHealth(self:getHealth())
    self.javaObject:setHealth(self.javaObject:getMaxHealth())
    local isMetal = self.style.skill == "MetalWelding"
    self.javaObject:setBreakSound(isMetal and "MetalGateBreak" or "WoodGateBreak")
    self.sq:AddSpecialObject(self.javaObject)
    buildUtil.consumeMaterial(self)
    AutoDoor.grantAccessories(getSpecificPlayer(self.player), self.keyId)
    self.javaObject:getModData().autoDoor = true
    self.javaObject:setKeyId(self.keyId)
    self.javaObject:transmitCompleteItemToClients()
end

function ISAutoFenceGate:partExists(square)
    if not square then return false end
    local spriteName = self.north and self.style.northSprite or self.style.sprite
    local objects = square:getSpecialObjects()
    for i = 1, objects:size() do
        local object = objects:get(i - 1)
        if instanceof(object, "IsoDoor") and
            object:getNorth() == self.north and
            not object:IsOpen() and
            object:getSprite() and object:getSprite():getName() == spriteName then
            return true
        end
    end
    return false
end

function ISAutoFenceGate:isValid(square)
    if not self:haveMaterial(square) then return false end
    if not square:hasFloor(self.north) then return false end
    if square:isVehicleIntersecting() then return false end
    if not self:partExists(square) and not square:isFreeOrMidair(false) then
        return false
    end
    if buildUtil.stairIsBlockingPlacement(square, true, self.north) then return false end
    return true
end

function ISAutoFenceGate:render(x, y, z, square)
    if self:partExists(square) then return end
    local spriteName = self.north and self.style.northSprite or self.style.sprite
    local sprite = IsoSprite.new()
    sprite:LoadSingleTexture(spriteName)
    if self:isValid(square) then
        sprite:RenderGhostTile(x, y, z)
    else
        sprite:RenderGhostTileRed(x, y, z)
    end
end

function ISAutoFenceGate:getHealth()
    return self.style.health
end

function ISAutoFenceGate:new(styleIndex)
    local o = {}
    setmetatable(o, self)
    self.__index = self
    o:init()
    o.style = AutoDoor.FENCE_GATE_STYLES[styleIndex]
    o:setSprite(o.style.sprite)
    o.northSprite = o.style.northSprite
    o.isDoor = true
    o.isWallLike = true
    o.thumpDmg = 5
    o.name = getText("IGUI_AutoDoor_FenceGate")
    o.keyId = ZombRand(100000, 999999)
    o.modData = AutoDoor.buildModData(o.style.materials)
    return o
end
